name: CI

on:
  push:
    branches: [ master, windows ]
  pull_request:
    branches: [ master, windows ]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Install dependencies
      run: vcpkg install sfml tgui sqlite3
    
    - name: Build
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 16 2019" ..
        msbuild ALL_BUILD.vcxproj -property:Configuration=Release
